[tool.poetry]
name = "advent-of-code"
version = "0.1.0"
description = ""
authors = ["Vitaly Legchilkin <vlegchilkin@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
numpy = "*"
requests = "^2.28.1"
html2text = "^2020.1.16"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
