[tool.poetry]
name = "advent-of-code"
version = "0.1.0"
description = "My 'Advent of Code' solutions"
authors = ["Vitaly Legchilkin <vlegchilkin@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.28.1"
ttp = "*"
addict = "*"
numpy = "*"
networkx = "*"
matplotlib = "*"
scipy = "*"
markdownify = "^0.11.6"
sympy = "^1.11.1"
llist = "^0.7.1"

[tool.poetry.dev-dependencies]
pytest = "^7.2.0"
pre-commit = { version = "*", source = "pypi" }
black = { extras = ["d"], version = "*", source = "pypi" }
coverage = { version = "^7.0.4", source = "pypi" }
html2image = { version = "*", source = "pypi" }

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
target-version = ['py310']

[tool.pytest.ini_options]
python_files = "*.py"
python_functions = "test_*"
addopts = "--ignore=utils --color=yes -s"
log_cli = "true"
log_cli_level = "debug"
log_format = "%(asctime)s | %(levelname)-7s | [%(name)s] %(message)s"
log_date_format = "%Y-%m-%d %H:%M:%S"
junit_family = "xunit1"
#asyncio_mode = "auto"
