[tool.poetry]
name = "advent-of-code"
version = "0.1.0"
description = ""
authors = ["Vitaly Legchilkin <vlegchilkin@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.28.1"
ttp = "^0.9.2"
addict = "^2.4.0"
numpy = "^1.23.5"
dijkstra = "^0.2.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
