[tool.poetry]
name = "advent-of-code"
version = "0.1.0"
description = ""
authors = ["Vitaly Legchilkin <vlegchilkin@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.28.1"
ttp = "*"
addict = "*"
numpy = "*"
networkx = "*"
matplotlib = "*"
scipy = "*"
markdownify = "^0.11.6"

[tool.poetry.dev-dependencies]
pytest = "^7.2.0"
pre-commit = { version = "*", source = "pypi" }
black = { extras = ["d"], version = "*", source = "pypi" }

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
target-version = ['py310']

[tool.pytest.ini_options]
python_files = "day_*.py"
python_functions = "test_*"
addopts = "--ignore=utils --color=yes"
#asyncio_mode = "auto"
