version: 2.1

orbs:
  python: circleci/python@2.1.1
  sonarcloud: sonarsource/sonarcloud@1.0.3

jobs:
  build-aoc-tests:
    parallelism: 4
    resource_class: small
    executor:
      name: python/default
      tag: "3.10"
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run AOC tests
          command: |
            set -e
            TEST_FILES=$(circleci tests glob "**/*.py" | circleci tests split --split-by=timings)
            mkdir -p test-results
            mkdir -p coverage-results
            poetry run coverage run -m pytest --log-cli-level=INFO --junitxml=test-results/junit.xml $TEST_FILES
            cp test-results/junit.xml coverage-results/junit-$CIRCLE_NODE_INDEX.xml
            cp .coverage coverage-results/.coverage.$CIRCLE_NODE_INDEX
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
      - persist_to_workspace:
          root: coverage-results
          paths:
            - "*"
  aggregate-sonar:
    resource_class: small
    executor:
      name: python/default
      tag: "3.10"
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - attach_workspace:
          at: coverage-results
      - run:
          name: Build Coverage Report
          command: |
            set -e
            mkdir -p test-results
            cp coverage-results/junit*.xml test-results
            mkdir -p coverage-reports
            poetry run coverage combine coverage-results/.coverage.0 coverage-results/.coverage.1 coverage-results/.coverage.2 coverage-results/.coverage.3
            poetry run coverage report
            poetry run coverage xml -o coverage-reports/coverage-overall.xml
      - store_artifacts:
          path: coverage-reports
      - sonarcloud/scan

workflows:
  main:
    jobs:
      - build-aoc-tests
      - aggregate-sonar:
          context: SonarCloud
          requires:
            - build-aoc-tests
