version: 2.1

orbs:
  python: circleci/python@2.1.1
  sonarcloud: sonarsource/sonarcloud@1.0.3

workflows:
  main:
    jobs:
      - python/test:
          pkg-manager: poetry
          version: "3.10"
      - sonarcloud/scan:
          context: SonarCloud
