version: 2.1

orbs:
  python: circleci/python@2.1.1
  sonarcloud: sonarsource/sonarcloud@1.0.3

jobs:
  build-test-sonar:
    parallelism: 4
    executor:
      name: python/default
      tag: "3.10"
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run tests
          command: |
            set -e
            TEST_FILES=$(circleci tests glob "aoc_*/day_*.py" | circleci tests split --split-by=timings)
            echo "$TEST_FILES"
            mkdir -p test-results
            poetry run pytest --junitxml=test-results/junit.xml $TEST_FILES
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
      - store_artifacts:
          path: coverage-reports
      - sonarcloud/scan


workflows:
  main:
    jobs:
      - build-test-sonar:
          context: SonarCloud
